### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by js1972** [udacity/self-driving-car-sim#1]
Instructions state to just git clone..? Now what?  ;-)

**Comment by deepmehtait** [comment]
@js1972 : Read me got updated.

**Comment by Christopheraburns** [comment]
Read the README.md file.  It is a text file usually found in every repository with information to help you get started.

This free course has content about Unity - the engine that "drives" the self-driving car sim.  Pun not intended.

**Comment by js1972** [comment]
Thanks @deepmehtait I see the readme has just been updated - perfect.
