### ISSUE TITLE
Can I try this projects on my Ubuntu?

### ISSUE THREAD

**Issue by yi2ha** [udacity/self-driving-car-sim#10]
Can I try this project on my Ubuntu?But Unity  just on win or mac.
And I try download beta-simulator-linux.zip ,then get beta_simulator.x86_64,beta_simulator.x86,beta_simulator_Data.

But I can't run it. Is that some steps or files I miss ? I love this project, hope for your help!

Version 2, 2/07/17

Linux beta_simulator.x86 this one do not work
./beta_simulator.x86_64: Permission denied
(have to run this,and now it work agian :)  chmod 777 ./beta_simulator.x86_64)

Version 1, 12/09/16

Linux Default Linux desktop Universal.x86_64 this one work!
relaybot@ubuntu:~/Downloads/simulator-linux$ ./Default\ Linux\ desktop\ Universal.x86_64
Set current directory to /home/relaybot/Downloads/simulator-linux
Found path: /home/relaybot/Downloads/simulator-linux/Default Linux desktop Universal.x86_64
Mono path[0] = '/home/relaybot/Downloads/simulator-linux/Default Linux desktop Universal_Data/Managed'
Mono path[1] = '/home/relaybot/Downloads/simulator-linux/Default Linux desktop Universal_Data/Mono'
Mono config path = '/home/relaybot/Downloads/simulator-linux/Default Linux desktop Universal_Data/Mono/etc'
displaymanager : xrandr version warning. 1.4
client has 3 screens
displaymanager screen (0)(LVDS1): 1366 x 768
Using libudev for joystick management

Importing game controller configs

**Comment by ilyes495** [comment]
Make sure the binary file has "execute permission"...
The easy way , right click in the file, then properties, go to the permissions tab and click in the "Allow executing file as program".
[https://i.stack.imgur.com/sFi9x.png](url)

**Comment by weiy1991** [comment]
Hi,  

I try to use this simulator on my ubuntu, I could run the linux_sim.84_64 and configure the param , but after I press the 'OK' button, the configuration closed and no software launched again, there's no error information. I don't know how to solve the problem.

**Comment by ARastogi19** [comment]
I have the same exact issue.

**Comment by kalyanperi** [comment]
Hey guys, Im in same position. Did u guys find any solution?

**Comment by MichaelYang21** [comment]
I have the same issue. Any solution for this one? Thanks

**Comment by robogeekcanada** [comment]
Any help will be appreciated. Thank you in advance.

**Comment by sgzzgit** [comment]
I have the same issue, feel sad.

**Comment by robogeekcanada** [comment]
I spent a lot of time on this and it's really tricky to make it work in Ubuntu. I am sure it's possible but I decided to start fresh with a Windows Server and it's working flawlessly. I also tried in AWS and Google Cloud with windows and works well.

**Comment by bhaveshkumarraj** [comment]
For those who are still facing problem in running this simulator on Ubuntu.
Use the older stable version of simulator(link given below). I tried on Ubuntu 16.04 and it worked.
https://d17h27t6h515a5.cloudfront.net/topher/2016/November/5831f0f7_simulator-linux/simulator-linux.zip

**Comment by laygond** [comment]
Hello bhaveshkumarraj are you able to run Term 2 - Project 5 - MPC with this simulator version? I get the following error and I want to know if the error is related to the simulator or something else.

laygond@laygond-VPCS111FM:~/karolmajekMPC/build$ ./mpc
factor_cte    2.000000
factor_epsi   5.000000
factor_v      0.100000
factor_steering 1000.000000
factor_throttle 0.100000
factor_seq_steering 30000.000000
factor_seq_throttle 1.000000
Listening to port 4567
Connected!!!
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be array, but is null
Aborted (core dumped)

**Comment by bhaveshkumarraj** [comment]
@laygond My requirement was to collect driving data to train the model. I just downloaded pre-compiled simulator using the link mentioned below. 
https://d17h27t6h515a5.cloudfront.net/topher/2016/November/5831f0f7_simulator-linux/simulator-linux.zip
I haven't worked on CarND-MPC-Project so I can't say anything about it.

**Comment by baumanab** [comment]
Closed since we have moved far beyond beta.
