### ISSUE TITLE
When trying to connect drive.py to model, "name 'npasarray' is not defined" error occurs

### ISSUE THREAD

**Issue by SohailSayed** [udacity/self-driving-car-sim#102]
I've trained my model and trying to connect it to the simulator model, but keep having this error:
![error123](https://user-images.githubusercontent.com/44615627/51611754-07989280-1eee-11e9-909c-1a002dbe765f.PNG)

**Comment by mvirgo** [comment]
This look like somewhere in your code you are trying to use `np.asarray` but didn't add the period after `np`

**Comment by SohailSayed** [comment]
That's odd, the only np.asarray is written with the period after np in my code
