### ISSUE TITLE
More realistic graphics

### ISSUE THREAD

**Issue by cTatu** [udacity/self-driving-car-sim#103]
I think that realistic graphics are fundamental for a simulator of autonomous cars. Does anyone know if it is something that had any priority for the near future?

**Comment by mvirgo** [comment]
Hi there! You should check out other simulators like [Nvidia's DRIVE Constellation](https://blogs.nvidia.com/blog/2018/09/12/drive-constellation-open-simulation/) for more realistic graphics. This simulator is in support of the Self-Driving Car Nanodegree program at Udacity only.
