### ISSUE TITLE
I cant open png files

### ISSUE THREAD

**Issue by zuoksrf** [udacity/self-driving-car-sim#12]
I downloaded zip.But i cant open png files, also project does not work on unity

**Comment by joystate** [comment]
Errors importing png and fbx files look like this:
`Could not create texture from Assets/Plugins/SimpleFileBrowser/Sprites/ImageFileIcon.png: File could not be read`

**Comment by joystate** [comment]
@zuoksrf , are you using `git lfs clone` and not `git clone`?

**Comment by baumanab** [comment]
Please use lfs, otherwise, not all files will be readable.
