### ISSUE TITLE
How can I use autonomodus mode to test my data?

### ISSUE THREAD

**Issue by TanLingxiao** [udacity/self-driving-car-sim#15]
I have successed installed the project and learned recording trained data,but when I enter autonomodus mode I don't what can I do to test the data or result.

**Comment by pedrocarrijo123** [comment]
With me , is the same problem :/

**Comment by pedrocarrijo123** [comment]
With me , is the same problem :/

**Comment by VinS101** [comment]
I'm late to the party, but did you guys find a solution?

**Comment by mvirgo** [comment]
Using autonomous mode is part of Project 3 of Term 1 - see the repository [here](https://github.com/udacity/CarND-Behavioral-Cloning-P3). Load your trained model in with `drive.py`.
