### ISSUE TITLE
Simulator crashes when run in VNC session

### ISSUE THREAD

**Issue by coventry** [udacity/self-driving-car-sim#22]
As I detailed in [#18](https://github.com/udacity/self-driving-car-sim/issues/18#issuecomment-290274876), Unity crashes when you try to open the linux simulator in a VNC session.

I'm not sure whether this is a simulator-specific issue, or a problem which affects Unity generally. [Someone had a related issue](http://answers.unity3d.com/questions/355646/unity-server-on-amazon-ec2-ubuntu.html) with a very simple Unity project, back in 2012.

**Comment by mvirgo** [comment]
Closing since this just relates to #18.
