### ISSUE TITLE
Simulator with Windows 7

### ISSUE THREAD

**Issue by rzanutta** [udacity/self-driving-car-sim#24]
I can not for company reasons upgrade to Windows 10, we use Windows 7 Premium. The simulator runs fine, until I try to record, then when I select the folder nothing else occurs. The menu selection just stays highlighted and no recording gets done. Is it possible to run the simulator with Windows 7, or is there user error on my part?

**Comment by mvirgo** [comment]
No further comments on this one; closing as a stale issue.
