### ISSUE TITLE
Training mode is missing on windows 10?

### ISSUE THREAD

**Issue by hzitoun** [udacity/self-driving-car-sim#34]
I've tried all the releases on my 64 bit windows 10 machine and none of them allowed me to record (pressing R key does nothing) because the exe, once opened, doesn't offer the posibility to choose "Training mode" as you can see here:

![issue](https://cloud.githubusercontent.com/assets/5884465/26451511/9c385004-415c-11e7-9fb6-de4948931cef.png)

Am I missing some config to enable the training mode?

**Comment by mvirgo** [comment]
The simulator you show above is for Term 2, not term 1. Training mode is only available in the Term 1 simulator.
