### ISSUE TITLE
Allowing adversaries, pedestrians and other assets

### ISSUE THREAD

**Issue by vamsiramakrishnan** [udacity/self-driving-car-sim#35]
I would like to **contribute** to add adversaries and pedestrians along with assets like traffic signs in the simulator. Please suggest how I can collaborate to make myself useful.

**Comment by desireend** [comment]
If possible, can you share the source code for  incorporating pedestrians and traffic system?

**Comment by vamsiramakrishnan** [comment]
Dear team

     I have not yet begun to work on this but I could be of help if that's
something you are looking to add on your roadmap . Currently I am trying to
do the following .  Use Pygame to incorporate a learning mechanism where
the data generated by the car in autonomous mode is used for training the
model further, also complemented by manual data in problem areas to speeden
the training process.

    I have no experience in unity but I would like to offer my support if
required for anything specific if you may need it .



Thanks and regards
Vamsi Ramakrishnan

**Comment by baumanab** [comment]
This sounds really cool.  Please let us know how this progresses.
