### ISSUE TITLE
This repository is over its data quota

### ISSUE THREAD

**Issue by keyvhinng** [udacity/self-driving-car-sim#36]
Hi, I'm facing the following issue when I try to clone:

Error downloading object: Assets/1_SelfDrivingCar/Sprites/Background.png (36e4565): Smudge error: Error downloading Assets/1_SelfDrivingCar/Sprites/Background.png (36e4565319a778a53538a2c1419174cac59597859e5a8616c1b94a08d6221ac3): batch response: **This repository is over its data quota**. Purchase more data packs to restore access.

Is the repository over its allotted data quota ?

**Comment by kodenusantara** [comment]
Yes I have this issue as well, I hope this get solved soon

**Comment by tuzzer** [comment]
I am hitting this issue as well.

**Comment by happyxujin** [comment]
I also have this issue.

**Comment by drganjoo** [comment]
I am also facing this issue. Tried forking this and even then its the same message.

**Comment by jwdunn1** [comment]
New month, same issue.

**Comment by f1yegor** [comment]
Just to mention for future reference, that you can download prebuild one https://github.com/udacity/self-driving-car-sim#avaliable-game-builds-precompiled-builds-of-the-simulator

**Comment by domluna** [comment]
Looks like Github has limits on git lfs usage https://help.github.com/articles/about-storage-and-bandwidth-usage/.

**Comment by drganjoo** [comment]
@f1yegor For some reason, the prebuilt windows simulator binary (for the 2nd term) does not connect over web sockets. I downloaded the src, rebuilt it and it successfully connects. However, the blue car doesn't appear and I am assuming that is happening because I don't have the LFS files.

The prebuilt simulator that does not connect was downloaded from: https://github.com/udacity/self-driving-car-sim/releases/download/v1.4/term2_sim_windows.zip

Thanks

**Comment by tuzzer** [comment]
The files sizes don't seem to be that big. Perhaps we can take them off LFS of it has data limit? 
I know that there is the precompiled version but I wanted the source so I can make changes to it. I was able to obtain a downloaded copy from someone else this time.

**Comment by happyxujin** [comment]
@tuzzer Do you mind sharing the source code copy?

**Comment by tuzzer** [comment]
@happyxujin Not sure how updated this was, but it worked for me.
https://1drv.ms/u/s!Ajjp7jQvYTaCjh7Rs9vmY99Vpccu

**Comment by fotiDim** [comment]
Yes that's the latest. All the commits are in. Thank you

**Comment by drganjoo** [comment]
@tuzzer thank you for sharing the code

**Comment by kdg1230** [comment]
@tuzzer Thanx :D

**Comment by Harry79** [comment]
@tuzzer Thx!

**Comment by xiumingxu** [comment]
That is great! Thaks

**Comment by cgarciae** [comment]
Thanks for sharing the code @tuzzer !!! 
How can this be fixed in general?

**Comment by skamranali** [comment]
@tuzzer Is the downloaded copy still in the same link? The page keeps loading and shows nothing.

**Comment by autonomobil** [comment]
same problem.. onedrive link doesn't work..

**Comment by baumanab** [comment]
This issue has been addressed and standard cloning is functional.

**Comment by AlexanderBollbach** [comment]
also having this issue

**Comment by lmzh97** [comment]
@MattChanTK Not reachable for me. Can I find it someplace in github?
