### ISSUE TITLE
Potential display bug in simulator v1.4

### ISSUE THREAD

**Issue by maschult** [udacity/self-driving-car-sim#38]
I can run the simulator and I see the car moving, but all the blue and red marks for the sensor data are not shown. The vicinity around the car remains simply white. If I also run my EKF-Code, I get a connection to the simulator but the symbols of my output are also not shown.

I'm using Debian Jessie (stable) with Xorg 7.7 and the proprietary Nvidia driver. Simulator version is 1.4. If you need further information, please let me know.

**Comment by Thyrland** [comment]
Hi maschult, any update on that?

**Comment by mvirgo** [comment]
No recent comments here - may have been due to changes in the project code around the same time. Closing out.
