### ISSUE TITLE
Error: TerrainData is missing & Lighting data asses is incompatible with current Unity version

### ISSUE THREAD

**Issue by vlchz** [udacity/self-driving-car-sim#39]
Please Help! 

When I did build & run I got the error "TerrainData is missing splat texture 1" but also missing texture 2, texture 0 etc. Below this is says "UnityEditor.HostView:OnGUI()"

The other error says Lighting data asset "LightingData" is incompatible with the current unity versio

**Comment by tuzzer** [comment]
Possibly related to this issue? https://github.com/udacity/self-driving-car-sim/issues/36

**Comment by mvirgo** [comment]
No recent comments here and appears this was likely related to #36, so closing out.
