### ISSUE TITLE
This repository is over its data quota. Purchase more data packs to restore access.

### ISSUE THREAD

**Issue by tomtran90** [udacity/self-driving-car-sim#41]
I got this error while trying git clone. I'm not sure if this is from my end or not.

>git clone https://github.com/udacity/self-driving-car-sim.git
Cloning into 'self-driving-car-sim'...
remote: Counting objects: 7608, done.
remote: Total 7608 (delta 0), reused 0 (delta 0), pack-reused 7608
Receiving objects: 100% (7608/7608), 132.32 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (1987/1987), done.
Checking connectivity... done.
Downloading Assets/1_SelfDrivingCar/Sprites/Background.png (6.83 MB)
Error downloading object: Assets/1_SelfDrivingCar/Sprites/Background.png (36e4565): Smudge error: Error downloading Assets/1_SelfDrivingCar/Sprites/Background.png (36e4565319a778a53538a2c1419174cac59597859e5a8616c1b94a08d6221ac3): batch response: This repository is over its data quota. Purchase more data packs to restore access.

**Comment by autodrive** [comment]
I also experience similar problem

**Comment by heidihysell** [comment]
+1 on this issue

**Comment by richadam** [comment]
+1 here too

**Comment by byett** [comment]
Same problem here, any fix?

**Comment by autonomobil** [comment]
any answer?

**Comment by ilyas156** [comment]
instead of cloning download this repository as a zip and unzip it.

**Comment by baumanab** [comment]
This issue has been resolved and cloning is working.
