### ISSUE TITLE
How do you get the car to automatically drive in autonomous mode once it is trained?

### ISSUE THREAD

**Issue by desireend** [udacity/self-driving-car-sim#42]
I am confused with this and wanted to figure this out.

**Comment by ffrige** [comment]
If you have trained a network to drive the car then you just need to send the steering angle and throttle calculated by the network to the simulator via telemetry. The script CommandServer.cs parses your data and sends it to the CarRemoteControl object.

**Comment by mvirgo** [comment]
Related to [this](https://github.com/udacity/self-driving-car-sim/issues/15) - the `model.py` file in the Project 3 repository should give you some hints.
