### ISSUE TITLE
Does not run in X11 Forwarded Mode - Feature Request

### ISSUE THREAD

**Issue by ashaik4** [udacity/self-driving-car-sim#44]
I am trying to run the Linux version of the simulator on the remote instance over ssh in X11 forward mode. The app only shows the initial settings screen and when clicked on start, it vanishes. 

Can we add a feature so that it can run in X11 forwarded mode? 

Thanks

**Comment by xie-dongping** [comment]
I think you would have enable [GLX on your X server](https://askubuntu.com/questions/745135/how-to-enable-indirect-glx-contexts-iglx-in-ubuntu-14-04-lts-with-nvidia-gfx), but I'm sure if a Unity program support that.

**Comment by baumanab** [comment]
Please try enabling glx on whichever X-server you are using.
