### ISSUE TITLE
Materials and/or textures seem to be missing

### ISSUE THREAD

**Issue by papiot** [udacity/self-driving-car-sim#45]
I cloned the repository using git lfs and it seems like I have all the files, however when I launch any scene, I don't see any materials and the UI looks broken. Any help much appreciated, I'd love to contribute to this project!
![self-driving-car-issue](https://user-images.githubusercontent.com/200760/28589479-a48e42a2-717e-11e7-8f14-42e7235bb63e.JPG)

**Comment by papiot** [comment]
You can see that the palm trees also don't have the materials showing up. Am I doing something wrong?

**Comment by spencerh-b** [comment]
Are you able to start the sim?

**Comment by autonomobil** [comment]
same problem..

**Comment by KDragos** [comment]
I cloned the repo and opened it with Unity version 2017.4.15f1. These issues seem to be fixed.

However, in your image, it seems like the source image somehow got disconnected. To fix this:
In the Inspector window (along the right hand side), click the little circle to the right of the box next to "Source Image". This should let you choose an image to put here.
The 1_BaseImageReference should be "drivingUI_Reference". 
The 1_BaseImage should be "drivingUI_Base"

**Comment by mvirgo** [comment]
No further comments; closing out.
