### ISSUE TITLE
problem with assets model

### ISSUE THREAD

**Issue by ninja93g** [udacity/self-driving-car-sim#5]
Hi,
What does it mean "please make sure to use Git LFS to properly pull over large texture and model assets."?

When I import the project Unity is not able to find some prefabs, I think that maybe is because I just used Unzip but I don´t really understand what Git is for...

**Comment by cfficaurzua** [comment]
Git lets you clone (download) all files from a repository (project folder), then easily update if changes where made, also allows you to make changes and contributions without compromise the original project, also it keeps track of all the changes made, so you can go back in history and restore the folder to a specific date. This works flawlessly with code scripts, but when you have large files containing only binary or hexadecimal data, git lacks of utility, thus git LFS manage to download those files from a server.
to run the simulator
follow this steps:
-install git https://git-scm.com/downloads
-then install git lfs https://git-lfs.github.com/
-reboot
-open the terminal or command prompt if you are in windows
go to the folder you want to download the material
write the following "git clone https://github.com/udacity/self-driving-car-sim.git" and then hit enter
if you correctly install git and git lfs then it should start to download every file, asset, image, etc 

finally  open unity-> open project-> select self-driving-car-sim from the folder you specified.
