### ISSUE TITLE
ROS Integration Simulator:  Player data archive not found

### ISSUE THREAD

**Issue by amakurin** [udacity/self-driving-car-sim#51]
`parallels@ubuntu:~/Downloads/lights_no_cars$ chmod +x ros_test.x86_64
parallels@ubuntu:~/Downloads/lights_no_cars$ ./ros_test.x86_64
Set current directory to /home/parallels/Downloads/lights_no_cars
Found path: /home/parallels/Downloads/lights_no_cars/ros_test.x86_64
Mono path[0] = '/home/parallels/Downloads/lights_no_cars/ros_test_Data/Managed'
Mono config path = '/home/parallels/Downloads/lights_no_cars/ros_test_Data/Mono/etc'
Preloaded 'ScreenSelector.so'`
 **`Player data archive not found at /home/parallels/Downloads/lights_no_cars/ros_test_Data/data.unity3d, using local filesystem`**
`parallels@ubuntu:~/Downloads/lights_no_cars$ cd ros_test_Data/
parallels@ubuntu:~/Downloads/lights_no_cars/ros_test_Data$ ls`

`boot.config                level3.resS                sharedassets1.assets
GI                         Managed                    sharedassets1.assets.resS
globalgamemanagers         Mono                       sharedassets2.assets
globalgamemanagers.assets  Plugins                    sharedassets2.assets.resS
level0                     Resources                  sharedassets2.resource
level1                     resources.assets           sharedassets3.assets
level2                     resources.assets.resS      sharedassets3.assets.resS
level2.resS                sharedassets0.assets       StreamingAssets
level3                     sharedassets0.assets.resS
`

**Comment by amakurin** [comment]
Ok this message is outputted before settings window appears. Then i choose lowest resolution and fastest quality. After clicking OK window disappears and that's it. No error. No message.

**Comment by ckirksey3** [comment]
@amakurin is this good to close? We also just released a new version of the ROS integration simulator that might fix this issue.

**Comment by amakurin** [comment]
yep Working on osx

**Comment by ckirksey3** [comment]
@amakurin we looked into this and determined that an issue with the OpenGL version that VirtualBox uses doesn't play nice with our simulator. The current options are to either use VMWare (which uses a more recent version of OpenGL) or run the virtual box natively on Windows/OSX and use port forwarding to communicate between ROS in your VM and the simulator on your native machine. Sorry about the inconvenience there. Please open a new issue if you run into problems with these other methods.

**Comment by veonua** [comment]
having the same issue on Ubuntu without VM
