### ISSUE TITLE
Term 3 Simulator Sources

### ISSUE THREAD

**Issue by dominikandreas** [udacity/self-driving-car-sim#52]
The sources of this repository don't seem to relate to the term 3 release (even the corresponding tags don't). Could somebody commit and push those sources and/or explain why this hasn't been done so far?

**Comment by happyguard91** [comment]
Yeah, could you please update the source code? I somehow managed to compile your term3 source code, but it turns out that the code is term 1 simulator source code

**Comment by Zireael07** [comment]
Where do I find the term 3 sources (the highway scene)?

**Comment by jokla** [comment]
Hi! Have you found the source code?

**Comment by mvirgo** [comment]
Please use the [Term 3 branch](https://github.com/udacity/self-driving-car-sim/tree/term3_collection).
