### ISSUE TITLE
How can I add the trained Neural network to the self-driving simulaltor ?

### ISSUE THREAD

**Issue by kangskii** [udacity/self-driving-car-sim#58]
Dear,
I have developed a well trained CNN. How could I combine my CNN code with the self-driving simulator ?
Thanks.

**Comment by mvirgo** [comment]
See the project repository for the third project of Term 1 of the Self-Driving Car Engineer Nanodegree program [here](https://github.com/udacity/CarND-Behavioral-Cloning-P3) - the `drive.py` file will let you import your model and use it to drive the car.
