### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by fusheng1990** [udacity/self-driving-car-sim#61]
hello,
I have a problem with the simulator. When I ran the code of EKF and the simulator term 2, there is an error of Segmentation fault (core dumped). I am sure the code is right. I do not know the reason lead to this problem? Could you give me some favor?

**Comment by baumanab** [comment]
Sorry for the technical issues.  The most effective way to resolve this is to discuss with a mentor.  If this does turn out to be a simulator bug please post the details here and we will reopen.

**Comment by AnukritiSinghh** [comment]
Hey, were you able to solve this?
