### ISSUE TITLE
remote control

### ISSUE THREAD

**Issue by beimingmaster** [udacity/self-driving-car-sim#62]
model predicting machine and car simulator machine is not the same, could i modify configuartion to do make a car driving test autonomously?

**Comment by mvirgo** [comment]
Hi there,

Can you clarify this Issue for me? It sounds potentially like you are mentioning that the MPC and Behavioral Cloning simulators are not the same, and wanting to see if MPC can be configured to drive autonomously like Behavioral Cloning is. If so, can you clarify what the need for this would be?

**Comment by mvirgo** [comment]
No further comments; closing.
