### ISSUE TITLE
Term2-PID: speed value is always positive, even in reverse.

### ISSUE THREAD

**Issue by frankcarey** [udacity/self-driving-car-sim#66]
While messing around with the bonus parts, i was going to try and handle the case where I apply a negative throttle (break) long enough, that the car ends up going in reverse. What I expected was that the speed value would go negative, but instead it just increases again.

**Comment by mvirgo** [comment]
Technically speed can't be negative - it has to have a positive or zero value, regardless of which direction it is occurring in. I do think a lot of simulators/games show this as negative to make things easier, but we'll pass on this for now.
