### ISSUE TITLE
incompatible with latest Unity?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [udacity/self-driving-car-sim#69]
I am not 100% sure if this is an incompatible issue. Could anyone kindly confirm that or shed some light on how to open the model correctly with Unity 2017.3 version? I'd like to modify the game by updating the car model. Thank you

**Comment by RameshKamath** [comment]
you have to clone with git-lfs to get all the files. It works even in unity 2018 version

**Comment by mvirgo** [comment]
No further comments, so closing out.
