### ISSUE TITLE
Problem with driving_log.csv

### ISSUE THREAD

**Issue by soaresinfo** [udacity/self-driving-car-sim#73]
I simulated on linux version but the file generated is messing with the numbers. The numeric output has commas instead of dots to separate the float portion, mixing with the fields separator. Either change the float separator to dots or change  the fields separator to semicolon.

**Comment by mvirgo** [comment]
Hi there! Please see the workaround [here](https://github.com/udacity/self-driving-car-sim/blob/master/simulator_issues_info.md) - this is a localization issue.
