### ISSUE TITLE
Self-Driving Car Simulator Version 1 source code

### ISSUE THREAD

**Issue by JosephChenHM** [udacity/self-driving-car-sim#78]
Hi, everyone
Is there any link or branch that I can download the source code of (Self-Driving Car Simulator Version 1, 12/09/16)? 
I can download version 2 source code; however, I need the second track environment in version 1.
I am trying to publish trajectory of the second track (not jungle track in Ver. 2) from simulator.
Thanks!!

**Comment by mvirgo** [comment]
You should be able to get to older versions by going backwards through the commit history.

**Comment by mvirgo** [comment]
Closing since no further comments in last month.
