### ISSUE TITLE
T3 simulator source code seems not right

### ISSUE THREAD

**Issue by Xunzhaocunzi** [udacity/self-driving-car-sim#79]
Hello, 

I downloaded the simulator term 3 source code and after I opened it, I found it was actually Term 1 simulator. The T3 simulator should be for the path planning project, right?

Could you upload the correct T3 simulator source code please? If I did not open the source correctly, would someone guide me how to use the source code? 

Any advice would be greatly appreciated.

**Comment by mvirgo** [comment]
@citlaligm Can you check on the Term 3 source code?

**Comment by mvirgo** [comment]
We have the correct source code on the [term3_collection](https://github.com/udacity/self-driving-car-sim/tree/term3_collection) branch, it appears.
