### ISSUE TITLE
beta version (feb) won't turn left or right with gamepad

### ISSUE THREAD

**Issue by rafiquemt** [udacity/self-driving-car-sim#8]
Get this version: https://d17h27t6h515a5.cloudfront.net/topher/2017/February/58983385_beta-simulator-mac/beta-simulator-mac.zip

Connect gamepad
Start simulator

**Expected:**
Be able to turn left and right with gamepad controller

**Actual:**
Can only go straight.

Details
OS: macOS. Tried Windows too
Gamepad: PS3 controller. Tried xbox one controller too

It works fine if you use the older version from November:
https://d17h27t6h515a5.cloudfront.net/topher/2016/November/5831f290_simulator-macos/simulator-macos.zip

**Comment by luqiang21** [comment]
Yes, that is true.

**Comment by baumanab** [comment]
Thank you.  Closing since we have moved far past beta.
