### ISSUE TITLE
How to open the limux_sim.x86 on Ubuntu?

### ISSUE THREAD

**Issue by davecerr** [udacity/self-driving-car-sim#86]
Hi,

I have an Ubuntu VM on a WIndows 10 host. I have cloned the CarND-Behavioral-Cloning-P3 repo. I then downloaded the linux-sim folder from the website and inside the linux-sim folder are three things:

1, linux_sim_Data folder

2, linux_sim.x86

3, linux_sim.x86_64

How do I run the executable files? I cannot open linux_sim.x86 and since this seems essential for the project I am essentially stuck. Do I need install a particular application or type something specific on the command line? Any help would be greatly appreciated!!!

**Comment by mvirgo** [comment]
No further comments, so assuming this is resolved. As Fadi mentioned above, you often have to give it permission with chmod, such as `chmod u+x`.
