### ISSUE TITLE
Prebuilt download link is not accessible

### ISSUE THREAD

**Issue by zhkmxx9302013** [udacity/self-driving-car-sim#92]
Excuse me, I've tried to open the link of Version2 Windows , but it didn't work. 
https://d17h27t6h515a5.cloudfront.net/topher/2017/February/58983318_beta-simulator-windows/beta-simulator-windows.zip

Is there any alternative link? thanks.

**Comment by mvirgo** [comment]
Unfortunately cloudfront is blocked in China - I'll try to look for if we have a separate link that works there, or otherwise switch over to AWS S3.

**Comment by mvirgo** [comment]
A little late, but the V2 links for Term 1 are now updated on the README to instead point to AWS.
