### ISSUE TITLE
Is it possible to use the 3'th party's Vehicle dynamics model

### ISSUE THREAD

**Issue by s894330** [udacity/self-driving-car-sim#94]
Hi ,

As the title say , could I use 3'rd party Vehicle dynamics model (like CarSim) to do simulation and they can communicate each other (for example: the car model created from CarSim can pass vihicle data to simulator, and the speed command data from simulator can pass to car model) ?
If the answer is "No" for now , would you have the plan to add this feature in the feature?

Thank you

**Comment by mvirgo** [comment]
As long as you are sending data to the correct port (typically 4567 for these simulators) and in the correct format, they can communicate with each other. It would be up to you to write the code necessary to make sure this is done (see [Behavioral Cloning](https://github.com/udacity/CarND-Behavioral-Cloning-P3/blob/master/drive.py) for an example in Python or [Extended Kalman Filter](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/blob/master/src/main.cpp) for an example in C++).

**Comment by mvirgo** [comment]
Closing out since no further comments in 2+ weeks.
